POST http://localhost:3001/api/notes 
Content-Type: application/json

{
    "content": "Esto es una nueva note",
    "important": true
}

###
POST http://localhost:3001/api/notes 
Content-Type: application/json

{
    
}
